### ISSUE TITLE
KeyError: 'Contents' on running upload

### ISSUE THREAD

**Issue by robmarkcole** [dogsheep/dogsheep-photos#32]
Following the readme, on big sur, and having entered my auth creds via `dogsheep-photos s3-auth`:

```
(venv) (base) Robins-MacBook:datasette robin$ dogsheep-photos upload photos.db     ~/Pictures/Photos\ /Users/robin/Pictures/Library.photoslibrary --dry-run

Fetching existing keys from S3...
Traceback (most recent call last):
  File "/Users/robin/datasette/venv/bin/dogsheep-photos", line 8, in <module>
    sys.exit(cli())
  File "/Users/robin/datasette/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/robin/datasette/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/robin/datasette/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/robin/datasette/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/robin/datasette/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/robin/datasette/venv/lib/python3.8/site-packages/dogsheep_photos/cli.py", line 96, in upload
    key.split(".")[0] for key in get_all_keys(client, creds["photos_s3_bucket"])
  File "/Users/robin/datasette/venv/lib/python3.8/site-packages/dogsheep_photos/utils.py", line 46, in get_all_keys
    for row in page["Contents"]:
KeyError: 'Contents'
```

Possibly since the bucket is in `EU (London) eu-west-2` and this into is not requested?

**Comment by dsisnero** [comment]
I am getting the same thing for US West (N. California) us-west-1

**Comment by aaronyih1** [comment]
Same here for US West (N. California) us-west-1

**Comment by aaronyih1** [comment]
The solution here is to upload an image to the bucket first. It is caused because it does not properly handle the case when there are no images in the bucket.
